- name: Install JDK and Maven and Git
  apt:
    name:
      - openjdk-8-jdk
      - maven
      - git
    update_cache: yes

- name: Clone project repository
  git:
    repo: ht/opt/hello-world/target/hello-1.0.war
    dest: /opt/hello-world
    version: master

- name: Build project
  shell: mvn package -f /opt/hello-world/pom.xml